name: "build"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: bazelbuild/setup-bazelisk@v1
    - name: Mount bazel cache
      uses: actions/cache@v2
      with:
        path: "~/.cache/bazel"
        # TODO(michaelmcallister): not sure what key to use here, things might
        # break if it gets executed on multiple hosts.
        key: ${{ runner.os }}-bazel
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install libpcap-dev
    # Build every single target in the project.
    - run: bazel build //...

  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Generate coverage profile
      run: go test -race -coverprofile=coverage.txt -covermode=atomic ./... 
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.txt
        fail_ci_if_error: true
